DEFAULT_FRONT_FACE_AREA_FRACTION = 1.0
DEFAULT_PHOTON_CUTOFF_KEV = 1.0
DEFAULT_ELECTRON_TRANSPORT = 'csda_straight_line'
DEFAULT_ELECTRON_RANGE_MODEL = 'tabata1994_compound_mean_ZA'
DEFAULT_MAX_ANGLE_DEG = 0.0
